# Generated by Django 5.2.4 on 2025-07-28 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funeraria', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientefuneraria',
            name='cliente_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='funeraria.funerariastatus', verbose_name='Status do Cliente'),
        ),
        migrations.AlterField(
            model_name='dependentefuneraria',
            name='dependente_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='funeraria.funerariastatus', verbose_name='Status do Dependente'),
        ),
        migrations.AlterField(
            model_name='funcionariofuneraria',
            name='first_name',
            field=models.CharField(max_length=150, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='funcionariofuneraria',
            name='last_name',
            field=models.CharField(max_length=150, verbose_name='Sobrenome'),
        ),
    ]
