# Generated by Django 5.2.4 on 2025-07-28 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funeraria', '0002_alter_clientefuneraria_cliente_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='funerariatipos',
            name='categoria',
            field=models.CharField(choices=[('plano', 'Plano'), ('servico', 'Serviço'), ('outro', 'Outro')], default='outro', max_length=50, verbose_name='Categoria do Tipo'),
        ),
        migrations.AddField(
            model_name='planofuneraria',
            name='tipo_plano',
            field=models.ForeignKey(default=1, limit_choices_to={'categoria': 'plano'}, on_delete=django.db.models.deletion.PROTECT, to='funeraria.funerariatipos', verbose_name='Tipo do Plano'),
            preserve_default=False,
        ),
    ]
