# Generated by Django 5.2.4 on 2025-07-28 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funeraria', '0003_funerariatipos_categoria_planofuneraria_tipo_plano'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientePlano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField(verbose_name='Data de Início')),
                ('data_fim', models.DateField(blank=True, null=True, verbose_name='Data de Fim')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cliente_planos', to='funeraria.clientefuneraria', verbose_name='Cliente')),
                ('funcionario_atualizacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cliente_planos_atualizados', to='funeraria.funcionariofuneraria', verbose_name='Funcionário que Atualizou')),
                ('funcionario_cadastro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cliente_planos_cadastrados', to='funeraria.funcionariofuneraria', verbose_name='Funcionário que Cadastrou')),
                ('plano', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cliente_planos', to='funeraria.planofuneraria', verbose_name='Plano Funerário')),
            ],
            options={
                'verbose_name': 'Cliente Plano',
                'verbose_name_plural': 'Clientes Planos',
                'db_table': 'cliente_plano',
                'ordering': ['-data_inicio'],
                'unique_together': {('cliente', 'plano', 'data_inicio')},
            },
        ),
    ]
