# Generated by Django 5.2.4 on 2025-07-28 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funeraria', '0004_clienteplano'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planofuneraria',
            name='tipo_renovacao',
            field=models.ForeignKey(limit_choices_to={'tipo__startswith': 'renovacao'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planos_com_renovacao', to='funeraria.funerariatipos', verbose_name='Tipo de Renovação'),
        ),
    ]
