# Generated by Django 5.2.4 on 2025-07-28 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funeraria', '0005_alter_planofuneraria_tipo_renovacao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='funerariatipos',
            options={'verbose_name': 'Funerária Tipo', 'verbose_name_plural': 'Funerária Tipos'},
        ),
        migrations.AddField(
            model_name='funerariatipos',
            name='valor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor'),
        ),
        migrations.AlterField(
            model_name='planofuneraria',
            name='tipo_renovacao',
            field=models.ForeignKey(limit_choices_to={'categoria': 'plano', 'descricao__startswith': 'Renovação'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planos_com_renovacao', to='funeraria.funerariatipos', verbose_name='Tipo de Renovação'),
        ),
        migrations.AlterField(
            model_name='servicoprestadofuneraria',
            name='tipo',
            field=models.ForeignKey(limit_choices_to={'categoria': 'servico', 'descricao__icontains': 'serviço'}, on_delete=django.db.models.deletion.PROTECT, to='funeraria.funerariatipos', verbose_name='Tipo de Serviço'),
        ),
    ]
