# Generated by Django 5.2.4 on 2025-07-29 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funeraria', '0007_formapagamento_alter_clienteplano_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagamentofuneraria',
            name='forma_pagamento',
        ),
    ]
