# Generated by Django 5.2.4 on 2025-07-29 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funeraria', '0008_remove_pagamentofuneraria_forma_pagamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clienteplano',
            name='data_fim',
            field=models.DateField(),
        ),
    ]
