# Generated by Django 5.2.4 on 2025-07-29 00:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funeraria', '0009_alter_clienteplano_data_fim'),
    ]

    operations = [
        migrations.AddField(
            model_name='funerariatipos',
            name='duracao_em_dias',
            field=models.IntegerField(blank=True, help_text='Quantos dias este tipo de renovação adiciona ao plano (somente para categoria "renovacao").', null=True, verbose_name='Duração em Dias (para Renovação)'),
        ),
        migrations.AlterField(
            model_name='clienteplano',
            name='data_fim',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Fim'),
        ),
        migrations.AlterField(
            model_name='dependentefuneraria',
            name='dependente_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='funeraria.dependentestatus', verbose_name='Status do Dependente'),
        ),
    ]
